# Generated by Django 5.1.6 on 2025-02-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('job_role', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('linkedin', models.URLField(max_length=255)),
                ('twitter', models.URLField(max_length=255)),
                ('startup_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('team_size', models.IntegerField()),
                ('website', models.URLField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='entrepreneur_profiles/')),
                ('reset_token', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_token_expiration', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('reset_token', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_token_expiration', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [],
            },
        ),
    ]
