# Generated by Django 5.1.6 on 2025-02-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('reset_token', models.CharField(blank=True, max_length=255, null=True)),
                ('reset_token_expiration', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [],
            },
        ),
    ]
