# Generated by Django 4.1.13 on 2025-03-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='pprofile_completion',
            field=models.IntegerField(default=0),
        ),
    ]
