# Generated by Django 4.1.13 on 2025-02-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_entrepreneur_bio_alter_entrepreneur_linkedin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, max_length=255, null=True)),
                ('firm_name', models.CharField(blank=True, max_length=255, null=True)),
                ('investment_stage', models.CharField(blank=True, max_length=255, null=True)),
                ('portfolio_size', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('min_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('max_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sectors', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='investor_profiles/')),
            ],
            options={
                'permissions': [],
            },
        ),
    ]
