# Generated by Django 4.1.13 on 2025-03-22 21:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_investor_pprofile_completion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investor',
            old_name='pprofile_completion',
            new_name='profile_completion',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='id',
        ),
        migrations.AddField(
            model_name='idea',
            name='custom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SavedIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.idea')),
            ],
            options={
                'unique_together': {('username', 'idea')},
            },
        ),
    ]
