# Generated by Django 4.1.13 on 2025-02-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
